#!/usr/bin/env node
/// Generates `src/generated/abis.ts` from Foundry build output in `packages/contracts/out`.
/// Run `forge build` in packages/contracts first, then `pnpm --filter @hume/sdk generate:abis`.
/// The generated file is checked in (Foundry's `out/` is gitignored), so CI and consumers do not
/// need a Foundry toolchain — only whoever changes a contract signature re-runs this script.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "../../contracts/out");
const target = resolve(here, "../src/generated/abis.ts");

/// contract name -> exported const name
const contracts = {
  MarketRegistry: "marketRegistryAbi",
  OracleRouter: "oracleRouterAbi",
  HumeVault: "vaultAbi",
  CollateralManager: "collateralManagerAbi",
  FeeManager: "feeManagerAbi",
  RiskManager: "riskManagerAbi",
  OptionsEngine: "optionsEngineAbi",
  OptionMarket: "optionMarketAbi",
  OptionPositionManager: "optionPositionManagerAbi",
  PerpsEngine: "perpsEngineAbi",
  PerpPositionManager: "perpPositionManagerAbi",
  PerpOrderManager: "perpOrderManagerAbi",
  FundingManager: "fundingManagerAbi",
  LiquidationEngine: "liquidationEngineAbi",
  InsuranceFund: "insuranceFundAbi",
  CrossMarginManager: "crossMarginAbi",
  SubaccountFactory: "subaccountFactoryAbi",
  Subaccount: "subaccountAbi",
  RFQManager: "rfqManagerAbi",
  HumePonsRouter: "ponsRouterAbi",
};

/// Contracts whose custom errors can surface through the contracts above (e.g. PriceValidator
/// reverts inside OracleRouter calls) but whose functions the SDK never calls directly.
const errorOnlyContracts = ["PriceValidator", "BuybackModule", "MockPriceFeed"];

const seenErrors = new Map();
let body = "";

function collectErrors(abi) {
  for (const item of abi) {
    if (item.type !== "error") continue;
    const signature = `${item.name}(${item.inputs.map((input) => input.type).join(",")})`;
    if (!seenErrors.has(signature)) seenErrors.set(signature, item);
  }
}

for (const [name, exportName] of Object.entries(contracts)) {
  const artifact = JSON.parse(readFileSync(resolve(outDir, `${name}.sol`, `${name}.json`), "utf8"));
  body += `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
  collectErrors(artifact.abi);
}

for (const name of errorOnlyContracts) {
  collectErrors(JSON.parse(readFileSync(resolve(outDir, `${name}.sol`, `${name}.json`), "utf8")).abi);
}

// Custom errors bubble up from nested calls (e.g. PerpsEngine -> RiskManager), so a single
// contract's own ABI cannot decode every revert; this merged list can.
body += `export const allErrorsAbi = ${JSON.stringify([...seenErrors.values()], null, 2)} as const;\n`;

const header = `// GENERATED by scripts/generate-abis.mjs from packages/contracts/out — do not edit by hand.\n\n`;
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, header + body);
console.log(`Wrote ${target} (${Object.keys(contracts).length} contracts, ${seenErrors.size} unique errors)`);
