/// One plain sentence plus one next action for every custom error the contracts can raise, keyed by the
/// error name the SDK decodes (`HumeContractError.errorName`). `revertReasons.test.ts` fails when the SDK's
/// error ABI gains an error that has no entry here, so a new revert can never reach a screen as a hex
/// string or a contract name.

/// Errors a person cannot cause or fix: setup, upgrade and access mistakes. Same words for all of them.
const OURS = "Something went wrong on our side. Nothing was changed. Try again in a moment.";
const NOT_YOURS = "This account is not allowed to do that. Nothing was sent. Switch to the wallet you used for it.";

export const revertReasons: Record<string, string> = {
  AccessControlBadConfirmation: NOT_YOURS,
  AccessControlUnauthorizedAccount: NOT_YOURS,
  AddressEmptyCode: OURS,
  AlreadyExists: "A trading account already exists for this wallet. Open it instead of creating another.",
  AlreadyRegistered: "That position is already part of your cross-margin account. Refresh and check your positions.",
  AlreadyTracked: "That token is already set up. Refresh the page.",
  BlockTooLarge: "This block trade is larger than the limit. Lower the size and try again.",
  CrossMarginDisabled: "Cross margin is not switched on for this market. Use isolated margin instead.",
  DeadlineExpired: "The order took too long to confirm. Submit it again.",
  ERC1967InvalidImplementation: OURS,
  ERC1967NonPayable: OURS,
  FailedCall: OURS,
  InsufficientCollateral: "Not enough available collateral. Deposit more or reduce the size.",
  InsufficientMargin: "The margin is too low for this size. Add collateral or lower leverage.",
  InsufficientPoolReserves: "The pool cannot pay this profit right now. Your position is still open. Try again in a few minutes.",
  InvalidBlockBounds: "That block trade range is not valid. Check the sizes and try again.",
  InvalidBps: "That fee setting is not valid. Nothing was changed.",
  InvalidDeviation: "The allowed price gap is not valid. Check it and try again.",
  InvalidExpiry: "That expiry is not available. Pick another expiry.",
  InvalidFactor: "That risk setting is not valid. Nothing was changed.",
  InvalidInitialization: OURS,
  InvalidLeverageTiers: "The leverage settings for this market are not valid. Try a lower leverage.",
  InvalidOraclePrice: "The price feed returned an invalid price. Try again shortly.",
  InvalidQuote: "The option price could not be verified. Request a new price and try again.",
  InvalidShock: "That stress test setting is not valid. Pick a smaller price move.",
  InvalidShortString: "That text is too long. Shorten it and try again.",
  InvalidTriggerPrice: "That trigger price does not fit the position. Set it on the other side of the current price and try again.",
  LengthMismatch: OURS,
  LimitPriceNotReached: "The price has not reached your limit yet. The order stays open until it does.",
  MarketAlreadyExists: "This market is already listed.",
  MarketDoesNotExist: "That market is not listed. Pick a market from the list.",
  MarketOraclePaused: "This market is paused. Try again once trading resumes.",
  MarketPaused: "This market is paused. Try again once trading resumes.",
  NetOpenInterestLimitExceeded: "Longs and shorts in this market are too far apart for this order. Try the other side or a smaller size.",
  NoPriceSource: "This market has no price yet, so it cannot trade. Try again shortly.",
  NotAuthorized: NOT_YOURS,
  NotInitializing: OURS,
  NotOptionOwner: "That option belongs to another wallet. Switch to the wallet that opened it.",
  NotOwner: NOT_YOURS,
  NotPositionOwner: "That position belongs to another wallet. Switch to the wallet that opened it.",
  NotQuoteUser: "That price was issued to another wallet. Request a new price and try again.",
  NotRfqManager: OURS,
  NotWorstPosition: "Another position is closer to liquidation and has to be handled first. Refresh and try again.",
  OpenInterestLimitExceeded: "The market's open interest limit is reached. Try a smaller size.",
  OptionNotOpen: "That option is already closed or settled. Refresh your positions.",
  OptionsNotEnabled: "Options are not available on this market. Trade its perpetual instead.",
  OrderExpired: "That order expired before it could fill. Place it again.",
  OrderNotFound: "That order no longer exists. Refresh your orders.",
  OrderNotOpen: "That order is already filled or cancelled. Refresh your orders.",
  PerpsNotEnabled: "Perpetuals are not available on this market. Try its options instead.",
  PositionAlreadyExpired: "That option has already expired. Settle it from your portfolio.",
  PositionLimitExceeded: "This size is above the position limit for the market. Lower the size.",
  PositionNotExpired: "That option has not expired yet, so it cannot be settled. Come back after its expiry time.",
  PositionNotFound: "That position was not found. Refresh your positions.",
  PositionNotLiquidatable: "That position is healthy, so it cannot be liquidated.",
  PositionNotOpen: "That position is already closed. Refresh your positions.",
  PremiumOutOfBounds: "The option price was outside the allowed range for the current market price. Request a new price and try again.",
  PriceOutOfBand: "That price is too far from the market price. Request a fresh price and try again.",
  ProtocolTokenNotSet: "This feature is not switched on yet. Nothing was changed.",
  QuoteAlreadyUsed: "That option price was already used. Request a new price and try again.",
  QuoteExpired: "The option price expired before it confirmed. Request a new price and try again.",
  ReentrancyGuardReentrantCall: OURS,
  RfqManagerAlreadySet: OURS,
  SafeERC20FailedOperation: "The token transfer was refused. Check your balance and the approval, then try again.",
  SettlementNotRecorded: "The settlement price for this expiry is not recorded yet. Try again in a few minutes.",
  SettlementNotYetDue: "This option cannot be settled yet. Come back after its expiry time.",
  SlippageExceeded: "The price moved past your slippage limit. Submit it again at the new price.",
  StaleOraclePrice: "The price feed is out of date, so orders are blocked. Try again shortly.",
  StringTooLong: "That text is too long. Shorten it and try again.",
  TargetNotAllowed: "A trading account cannot call that address. Nothing was sent.",
  TooManyCrossPositions: "Your cross-margin account holds the most positions it can. Close one first.",
  TooManyPortfolioOptions: "Your account holds the most options it can. Close or settle one first.",
  TooManyShocks: OURS,
  TriggerPriceNotReached: "The price has not reached your trigger yet. The order stays in place until it does.",
  UUPSUnauthorizedCallContext: OURS,
  UUPSUnsupportedProxiableUUID: OURS,
  UnsupportedToken: "That token cannot be used as collateral. Pick a supported one.",
  WithdrawWouldUndermargin: "Withdrawing that much would leave your positions under-margined. Withdraw less or close a position first.",
  ZeroAddress: OURS,
  ZeroAmount: "The amount cannot be zero. Enter an amount and try again.",
  ZeroBatch: OURS,
};

/// An error the map does not know: a generic sentence plus the contract's error name, never hex.
export function revertReason(errorName: string): string {
  return revertReasons[errorName] ?? `That did not go through (${errorName}). Nothing was lost. Try again, and tell us if it keeps happening.`;
}
